
name: CI
on:
  push:
      branches: [main]
      paths-ignore:
        - '**/README.md'
  pull_request:
    branches: [main]
jobs:
  # # flutter_test:
  #   name: Run flutter test and analyze
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3.3.0
  #     - uses: actions/setup-java@v3.9.0
  #       with:
  #         java-version: "17"
  #         distribution: 'temurin'
  #     - uses: subosito/flutter-action@v2.8.0
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter test
  build:
    name: Android APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
    - name: Setup Flutter
      uses: subosito/flutter-action@v2.8.0
    - run: flutter pub get
    - name: Build APK
      run: flutter build apk --release
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: test.apk
        path: build/app/outputs/apk/release/app-release.apk
    - run: flutter clean

  # build_ios:
  #   name: IOS iPA
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3.3.0
  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2.8.0
  #   - run: flutter pub get
  #   - name: Build iOS
  #     run: flutter build ios 
  #   - name: Archive
  #     run: xcrun xcodebuild -sdk iphoneos -scheme Runner archive -archivePath build/Runner.xcarchive
  #   - name: Export
  #     run: xcrun xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportPath build -exportOptionsPlist ios/exportOptions.plist
  #   - name: Upload IPA
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: Runner.ipa
  #       path: build/Runner.ipa
  #   - run: flutter clean
